name: flutter_application_simko
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  image_picker: ^1.0.4
  mime: ^1.0.4
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/simko_logo.png
    - assets/kost1.jpg
    - assets/kost2.jpg
    - assets/kost3.jpg
